### ISSUE TITLE
White screen in avd and real device

### ISSUE THREAD

**Issue by Fireballlion** [shaqian/flutter_realtime_detection#10]
Hi.
I have downloaded the repo but when i run it in my android studio ,v3.5, all i get in my emulator/real device is a white screen when opening the app and the console just says "E/BpSurfaceComposerClient(10222): Failed to transact (-1)
E/BpSurfaceComposerClient(10222): Failed to transact (-1)"
. Any help with this would be greatly appreciated.

**Comment by farshed** [comment]
@Fireballlion I'm facing the same issue. Did you find a workaround?
