### ISSUE TITLE
Quick, newbie question

### ISSUE THREAD

**Issue by lezg0** [shaqian/flutter_realtime_detection#11]
Hey!
I'm just starting to use Flutter por object recognition and i would like to know how can i try this code for myself. I'm using Android Studio, and I don't know what to do or open. Thanks in advance, I know this is a very silly question, but I'm a quick learner, promise :)

**Comment by kurtjcu** [comment]
@lezg0 you will have to install flutter and the android SDK for your target device. Then open the project and run "flutter pub get" to get the dependencies.

**Comment by shaqian** [comment]
Archiving this thread. Feel free to reopen if you have further questions.

Thanks,
Qian
