### ISSUE TITLE
Example fails to load on iOS 13

### ISSUE THREAD

**Issue by kenthinson** [shaqian/flutter_realtime_detection#13]
debug output
`Launching lib/main.dart on Kent Hinson’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: L2F5C82287
Xcode build done.                                           11.5s
Checking for advertised Dart observatories...
Checking for available port on com.example.exampleRealtime._dartobservatory._tcp.local
Checking for authentication code for com.example.exampleRealtime._dartobservatory._tcp.local`

Crash happens during app launch trying to access the camera. I'm guessing it's a permissions issue.

`Exception has occurred.
FlutterError (ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.)`

The popup asking for camera permission never showed on the phones screen.

**Comment by shaqian** [comment]
Hi Kent,

The error looks similar to https://github.com/flutter/flutter/issues/40253#issuecomment-530391344
Can you try adding `WidgetFlutterBinding.ensureInitialized()` in the first line in main()?

Thanks,
Qian

**Comment by shaqian** [comment]
Archiving this thread. Feel free to reopen if you have further questions.

Thanks,
Qian
