### ISSUE TITLE
Error while  doing release build.

### ISSUE THREAD

**Issue by Techno-Disaster** [shaqian/flutter_realtime_detection#17]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':tflite:verifyReleaseResources'.             
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/merged/release/values/values.xml:186: error: resource android:attr/fontVariationSettings not found.
  /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/merged/release/values/values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                                                                        
  Command: /home/Techno-Disaster/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/06fcfe37f7cce96046824d41c1d91cd9/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/Techno-Disaster/Android/Sdk/platforms/android-27/android.jar\
          --manifest\                                                   
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/aapt_friendly_merged_manifests/release/processReleaseManifest/aapt/AndroidManifest.xml\
          -o\                                                           
          /tmp/aapt-28206924259168528-out\                              
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-cs_values-cs.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-xhdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-sq_values-sq.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-da_values-da.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ne_values-ne.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-in_values-in.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-vi_values-vi.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-fi_values-fi.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-hr_values-hr.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-bn_values-bn.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-pt-rPT_values-pt-rPT.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-tr_values-tr.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-gl_values-gl.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-hdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ta_values-ta.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-en-rXC_values-en-rXC.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_normal.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-nl_values-nl.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-be_values-be.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ru_values-ru.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-as_values-as.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-sv_values-sv.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout_notification_action_tombstone.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-sr_values-sr.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ur_values-ur.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-fr_values-fr.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values_values.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-zh-rTW_values-zh-rTW.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-si_values-si.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_normal.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-de_values-de.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-lt_values-lt.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-lo_values-lo.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ar_values-ar.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout-v16_notification_template_custom_big.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ms_values-ms.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-az_values-az.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable_notification_icon_background.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ky_values-ky.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-sl_values-sl.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-zu_values-zu.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-b+sr+Latn_values-b+sr+Latn.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable_notification_tile_bg.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-it_values-it.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable_notification_bg.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-kn_values-kn.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ja_values-ja.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-uk_values-uk.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-fr-rCA_values-fr-rCA.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-es-rUS_values-es-rUS.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-mdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-en-rAU_values-en-rAU.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-is_values-is.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-my_values-my.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ro_values-ro.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-pa_values-pa.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-pt_values-pt.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-mr_values-mr.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-en-rGB_values-en-rGB.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-te_values-te.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-el_values-el.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-et_values-et.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ko_values-ko.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-or_values-or.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-pl_values-pl.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-nb_values-nb.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout_notification_action.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-gu_values-gu.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-fa_values-fa.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ca_values-ca.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-en-rCA_values-en-rCA.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-bg_values-bg.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-eu_values-eu.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-sk_values-sk.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout-v21_notification_template_icon_group.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout-v21_notification_action.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-pt-rBR_values-pt-rBR.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-hu_values-hu.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-sw_values-sw.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-es_values-es.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-lv_values-lv.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-mn_values-mn.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout-v21_notification_template_custom_big.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-mk_values-mk.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-kk_values-kk.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-tl_values-tl.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ml_values-ml.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout-v21_notification_action_tombstone.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable_notification_bg_low.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-v21_notification_action_background.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-th_values-th.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-am_values-am.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-iw_values-iw.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-uz_values-uz.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-af_values-af.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout_notification_template_part_chronometer.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-bs_values-bs.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-zh-rCN_values-zh-rCN.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-en-rIN_values-en-rIN.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-hy_values-hy.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-km_values-km.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-v16_values-v16.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-zh-rHK_values-zh-rHK.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-ka_values-ka.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout_notification_template_icon_group.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_normal.9.png.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-v21_values-v21.arsc.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/layout_notification_template_part_time.xml.flat\
          -R\                                                           
          /home/Techno-Disaster/Flutter/apps/PlushieMate/build/tflite/intermediates/res/compiled/release/values-hi_values-hi.arsc.flat\
          --auto-add-overlay\                                           
          --non-final-ids\                                              
          -0\                                                           
          apk\                                                          
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0                    
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 11s

**Comment by Techno-Disaster** [comment]
# Solution: 
add this in your project/build.gradle
subprojects {
    project.evaluationDependsOn(':app')
        afterEvaluate {project ->
            if (project.hasProperty("android")) {
                android {
                    compileSdkVersion 28
                    buildToolsVersion '28.0.3'
                }
                configurations.all {
                    resolutionStrategy { 
                        force 'com.google.android.gms:play-services-gcm:16.1.0'
                        force 'com.google.android.gms:play-services-location:16.0.1'
                        force 'com.google.android.gms:play-services-basement:16.2.0'
                        force 'com.google.android.gms:play-services-auth:16.0.1'
                        force 'com.google.android.gms:play-services-stats:16.0.1'
                        force 'com.google.android.gms:play-services-base:16.0.1'
                    }
                }
            }
        }
    
} // this is for release build

**Comment by eduardkieser** [comment]
Thanks so much man. This seems to do the trick. Will test with a device when I get home tonight.

**Comment by Techno-Disaster** [comment]
Leave a like of it helped you 🙂

**Comment by eduardkieser** [comment]
I do still get this message though:
```
Note: /Users/eduard/development/flutter/.pub-cache/hosted/pub.dartlang.org/tflite-1.0.4/android/src/main/java/sq/flutter/tflite/TflitePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
In red text, is this a known thing? Should I be worried?

**Comment by Techno-Disaster** [comment]
just a warning, @shaqian can fix it easily.

**Comment by Techno-Disaster** [comment]
@shaqian  i have sent a PR with the solution. Kindly take a look. Thank You

**Comment by iyuhang** [comment]
I add this to build.gradle

subprojects {
project.evaluationDependsOn(':app')
afterEvaluate {project ->
if (project.hasProperty("android")) {
android {
compileSdkVersion 28
buildToolsVersion '28.0.3'
}
configurations.all {
resolutionStrategy {
force 'com.google.android.gms:play-services-gcm:16.1.0'
force 'com.google.android.gms:play-services-location:16.0.1'
force 'com.google.android.gms:play-services-basement:16.2.0'
force 'com.google.android.gms:play-services-auth:16.0.1'
force 'com.google.android.gms:play-services-stats:16.0.1'
force 'com.google.android.gms:play-services-base:16.0.1'
}
}
}
}

}

it reports

FAILURE: Build failed with an exception.

What went wrong:
Could not determine the dependencies of task ':location:compileReleaseAidl'.
Could not resolve all task dependencies for configuration ':location:releaseCompileClasspath'.
Could not find com.google.android.gms:play-services-location:16.0.1.
Required by:
project :location

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 2m 53s

**Comment by iyuhang** [comment]
@Techno-Disaster any ideas?

**Comment by Techno-Disaster** [comment]
@iyuhang  take a look at my repo [here](https://github.com/Techno-Disaster/PlushieMate)

**Comment by iyuhang** [comment]
@Techno-Disaster sorry, I could not find any solution, you can build andoird release in flutter 12.13 ?

**Comment by Techno-Disaster** [comment]
12.13? 
I'm on 1.14 and it builds successfully

**Comment by MATTYGILO** [comment]
> I add this to build.gradle
> 
> subprojects {
> project.evaluationDependsOn(':app')
> afterEvaluate {project ->
> if (project.hasProperty("android")) {
> android {
> compileSdkVersion 28
> buildToolsVersion '28.0.3'
> }
> configurations.all {
> resolutionStrategy {
> force 'com.google.android.gms:play-services-gcm:16.1.0'
> force 'com.google.android.gms:play-services-location:16.0.1'
> force 'com.google.android.gms:play-services-basement:16.2.0'
> force 'com.google.android.gms:play-services-auth:16.0.1'
> force 'com.google.android.gms:play-services-stats:16.0.1'
> force 'com.google.android.gms:play-services-base:16.0.1'
> }
> }
> }
> }
> 
> }
> 
> it reports
> 
> FAILURE: Build failed with an exception.
> 
> What went wrong:
> Could not determine the dependencies of task ':location:compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':location:releaseCompileClasspath'.
> Could not find com.google.android.gms:play-services-location:16.0.1.
> Required by:
> project :location
> 
> Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 53s

I just commented out 
//                    force 'com.google.android.gms:play-services-location:16.0.1'
and it works
