### ISSUE TITLE
tensorflow lib error

### ISSUE THREAD

**Issue by wiexin** [shaqian/flutter_realtime_detection#2]
![](https://files.gitter.im/flutter/flutter/vYd4/image.png)

When I installed this warehouse, I encountered a problem. It needs a library of tensorflow, but I don't know how to install it. I tried to ask the official questions in the past, but no one answered me. I am a novice flutter.

**Comment by shaqian** [comment]
Hi Wiexin,
Can you go to ios directory and run `pod install`?

**Comment by Arashf** [comment]
pod install run successfully but error don't go away

**Comment by shaqian** [comment]
If you are using a later version of tensorflow lite, the error may be caused by the changes in the header path. You can try the resolution in this PR. https://github.com/shaqian/flutter_tflite/pull/17

**Comment by lonelygo** [comment]
In pubspec.yaml file modify tflite: 1.0.1 to 1.0.3 can fix it.

**Comment by shaqian** [comment]
Temporarily archiving the thread. Feel free to reopen if you still have the issue.
